### ISSUE TITLE
buf 0.18.0 crashes with runtime error when a file has a proto extension but garbage content

### ISSUE THREAD

**Issue by twiz718** [bufbuild/buf#120]
* Ubuntu 20.04
* Download https://github.com/bufbuild/buf/releases/download/v0.18.0/buf-Linux-x86_64

```
$ cat 1/2/foo.proto/ddd.proto
asda
```

```
cat buf.yaml 
lint:
  use:
    - DEFAULT
  except:
    - PACKAGE_VERSION_SUFFIX
    - FILE_LAYOUT
    - RPC_REQUEST_STANDARD_NAME         # because of Connect method
    - RPC_RESPONSE_STANDARD_NAME        # because of Connect method
  rpc_allow_same_request_response: true # because of Connect method
breaking:
  use:
    - FILE
```

```
buf check lint
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9caf8b]

goroutine 6 [running]:
github.com/jhump/protoreflect/desc/protoparse.(*basicCompositeNode).start(...)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/ast.go:162
github.com/jhump/protoreflect/desc/protoparse.(*parseResult).createFileDescriptor(0xc000271f20, 0xc000305720, 0x17, 0xc00032a540)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/descriptor_protos.go:35 +0xd9b
github.com/jhump/protoreflect/desc/protoparse.createParseResult(0xc000305720, 0x17, 0xc00032a540, 0xc000271ec0, 0xc000073a40)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/parser.go:690 +0xba
github.com/jhump/protoreflect/desc/protoparse.parseProto(0xc000305720, 0x17, 0x7fb5c9ad43f8, 0xc0002d8aa0, 0xc000271ec0, 0xc000308401, 0xc0002d8a90)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/parser.go:669 +0x16e
github.com/jhump/protoreflect/desc/protoparse.parseProtoFile.func2(0x7fb5c9ad4438, 0xc0002d8aa0, 0xc000305720, 0x17, 0xc000271ec0, 0x1, 0xc000061b20)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/parser.go:440 +0xba
github.com/jhump/protoreflect/desc/protoparse.parseProtoFile(0xc000061cd0, 0xc000305720, 0x17, 0x0, 0xc000271ec0, 0x400101, 0xc000061cb0, 0xc2d160)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/parser.go:441 +0x964
github.com/jhump/protoreflect/desc/protoparse.parseProtoFiles(0xc000061cd0, 0xc0003012a0, 0x2, 0x2, 0xc000271ec0, 0x101, 0xc000061cb0, 0x0)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/parser.go:414 +0xb9
github.com/jhump/protoreflect/desc/protoparse.Parser.ParseFiles(0xc0002d8a90, 0x1, 0x1, 0x0, 0x0, 0xc000308480, 0x1, 0xc000301320, 0x0, 0xc0003012a0, ...)
	github.com/jhump/protoreflect@v1.6.2-0.20200602154950-9a9113f80b57/desc/protoparse/parser.go:207 +0x1bc
github.com/bufbuild/buf/internal/buf/bufbuild.getBuildResult(0xd18040, 0xc000073a40, 0x7fb5c9ad43c0, 0xc0002b5360, 0x7fb5c9ad4418, 0xc0002d8650, 0xc0002d8a90, 0x1, 0x1, 0xc0003012a0, ...)
	github.com/bufbuild/buf/internal/buf/bufbuild/builder.go:210 +0x202
github.com/bufbuild/buf/internal/buf/bufbuild.(*builder).getBuildResults.func1(0xc00032a3c0, 0xd18040, 0xc000073a40, 0x7fb5c9ad43c0, 0xc0002b5360, 0x7fb5c9ad4418, 0xc0002d8650, 0xc0002d8a90, 0x1, 0x1, ...)
	github.com/bufbuild/buf/internal/buf/bufbuild/builder.go:148 +0xcd
created by github.com/bufbuild/buf/internal/buf/bufbuild.(*builder).getBuildResults
	github.com/bufbuild/buf/internal/buf/bufbuild/builder.go:147 +0x31f
```

**Comment by bufdev** [comment]
This was fixed in 0.20.4, upgrade and you're good to go!
