### ISSUE TITLE
Panic/race condition on buf generate with a missing(?) plugin

### ISSUE THREAD

**Issue by titpetric** [bufbuild/buf#835]
From the CI:

```
[codegen:22] buf generate --path rpc
[codegen:23] panic: send on closed channel
[codegen:24] 
[codegen:25] goroutine 88 [running]:
[codegen:26] github.com/bufbuild/buf/private/buf/bufgen.semaphore.Acquire(0xc000ad91a0, 0x1082448, 0xc000e85080, 0xc0002ec6e0, 0x108a248)
[codegen:27] 	/go/pkg/mod/github.com/bufbuild/buf@v0.56.0/private/buf/bufgen/generator.go:553 +0x9e
[codegen:28] github.com/bufbuild/buf/private/buf/bufgen.(*generator).generateConcurrently.func1(0x0, 0x0)
[codegen:29] 	/go/pkg/mod/github.com/bufbuild/buf@v0.56.0/private/buf/bufgen/generator.go:228 +0xcf
[codegen:30] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000dcbce0, 0xc000e835e0)
[codegen:31] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
[codegen:32] created by golang.org/x/sync/errgroup.(*Group).Go
[codegen:33] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
[codegen:34] make: *** [Makefile:69: rpc] Error 2
```

or, rerunning it:

```
[codegen:22] buf generate --path rpc
[codegen:23] Failure: failed to generate plugins concurrently: failed to create handler: could not find protoc plugin for name twirp-swagger.
[codegen:24] make: *** [Makefile:69: rpc] Error 1
```

I asume the second output is the desired output, and the panic in the first one is due to a race condition over some locking structures.

**Comment by amckinney** [comment]
It looks like you're on an older version of `buf` - would you mind upgrading to the latest release? https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc10

**Comment by amckinney** [comment]
Your error might still exist after the upgrade, but it probably won't be a panic (this issue was resolved earlier).

From the message, it looks like `protoc-gen-twirp-swagger` is not available on the CI runner's `PATH`, so you might need to add some extra setup steps to get things working.

**Comment by titpetric** [comment]
I am running rc10. Just "installed" today.

**Comment by titpetric** [comment]
Obviously the cause of the issue was my setup, if the panic was fixed in/before rc10, I'm closing this as invalid.
